### ISSUE TITLE
Not compatible with High-Performance Order Storage

### ISSUE THREAD

**Issue by Levdbas** [myparcelnl/woocommerce#1113]
### Plugin version

4.2.22

### WooCommerce version

8.9.2

### WordPress version

 6.5.4

### PHP version

8.2

### What went wrong?

With a newly setup webshop that automatically setups for High performant orders, Myparcel does not work anymore.

### Reproduction steps

1. setup new webshop with high performant orders enabled
2. setup myparcel
3. see that metaboxes on order details and barcode columns are not rendering.

### Additional context

> From WooCommerce 8.2, released on October 2023, [High-Performance Order Storage (HPOS)](https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/) is officially flagged as stable and will be enabled by default for new installations.

https://woocommerce.com/document/high-performance-order-storage/

I would expect such a big new feature would be supported by this plugin after being stable and default for so long. I just wasted so much time debugging this.

**Comment by mxxrten** [comment]
Very sad indeed. I updated to 4.23.0 and read what's new, I first saw the word HPOS and was happy, only to find out it adds a warning it doesn't work with HPOS. How could it not have a warning before and still not work with HPOS?  😞

**Comment by RichardPerdaan** [comment]
Unfortunately, we do not support HPOS with version 4.23. However, we do support HPOS with our beta plugin, which you can download via our GitHub page ([v5.0.0-beta.8](https://github.com/myparcelnl/woocommerce/releases/tag/v5.0.0-beta.8))

This beta version is a completely new plugin, which is why we are cautious about making this version live. Over the past few months, we have been working hard to make this beta as stable as possible.

We encourage you to test the beta plugin and share any feedback with us so we can further optimize the plugin.

**Comment by EdieLemoine** [comment]
HPOS is supported in [v5.0.0](https://github.com/myparcelnl/woocommerce/releases/tag/v5.0.0).
