### ISSUE TITLE
Woocommerce admin order load really slow

### ISSUE THREAD

**Issue by aprwebdesign** [myparcelnl/woocommerce#21]
With the myparcel plugin active the orders inside wp-admin loads really really slow.

When i disable the plugin ( to test) the orders load within 3seconds.
When enabled it takes about 30 seconds to load.

Is there a quick fix for this?

my entire website is blazing fast and it is really sad that i can't just load and/or edit within a few seconds.

**Comment by aprwebdesign** [comment]
i discovered that the slow loading is caused by the public function order_list_shipment_options in class-wcmp-admin.php file

when commenting this line: $consignments = $this->get_order_shipments( $order, true ); 
the loading speed is the same as without the plugin active.

the problem however is that when i comment the above line the tracking status is not displayed.

**Comment by aprwebdesign** [comment]
Instead of commenting $consignments i have commented the follow line: 

$shipment = WooCommerce_MyParcel()->export->get_shipment_data( $last_shipment_id, $order );
It is located on line 52 inside  class-wcmp-admin.php 

The loading speed is now acceptable but i not yet can figure out what option is disabled by commenting this line. 

It all looks fine. 

Will report if any problems arise because i have commented this line

**Comment by aprwebdesign** [comment]
**I Found the the reason for the slow loading time.**

The slow loading time on the order overview page is caused by the track and trace codes.

By commenting out the line above you cannot view the track and trace code on the overview page.

When viewing an product individual you can still see the track and trace code.

For me this is acceptable because i do not have to wait for the orders to load.
When i want to see the track and trace this is just on click away.

**> Maybe a solution for this issue would be to store the track and trace code inside a meta field when an order is exported.
> 
> This will prevent a delay when loading the track and trace codes from postNL**

**Comment by Spreeuw** [comment]
Hi! Thanks for sharing your findings! Although I wouldn't call 3 seconds 'blazing fast', 30 seconds is definitely ridiculously slow.

The track & trace code is actually stored in the order meta already, the connection with the MyParcel API is not to retrieve this, but to update the shipment status shown (pending/en route/delivered etc).

I have not experienced slowness caused by this in any of the sites I have worked with (seen many client sites), so I think it's partly caused by the server too. I recommend looking into this, a normal plain text curl call should be very light.

That said, I agree that some sort of caching mechanism would be nice, using wordpress transients to limit retrieving this information to a specific interval (say, 15 minutes or 1 hour).

**Comment by RichardPerdaan** [comment]
The speed has been improved in version 3.0.2 of the plugin

**Comment by MIOsystems** [comment]
Is there still attention for this issue? As we noticed also a great delay caused by this plugin. Please investigate furter with verzion 4.22.1. And let me known what info you need to track it down.

![MyParcel plugin](https://github.com/myparcelnl/woocommerce/assets/46918729/1330e831-761a-4c7c-b411-7b5b99867761)
