### ISSUE TITLE
Order view in backend fails when myparcel API is not available.

### ISSUE THREAD

**Issue by onlinemusketeers** [myparcelnl/woocommerce#282]
It seems that when the API is offline, processed orders in woocommerce backend are not available due to error(s)
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in 
public_html/wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php:138

Unavailability of the rest api should not break the admin of woocommerce

Another unwanted behaviour is the unavailability of the location service for "afhalen bij PostNL punt".
This breaks the most important part of the shop, the checkout. 

Please built in a check for availability of your API so it doesn't break the important functionality of the backend and frontend.

**Comment by RichardPerdaan** [comment]
Hi @onlinemusketeers ,

At the moment I am working on a fix for this problem. 
This fix will be included in the next version of the MyParcel plugin. 
For a quick temporary solution, I will advise you to turn off the MyParcel delivery options.

**Comment by onlinemusketeers** [comment]
Hi Richard, it looks like this has been since august  [#275](https://github.com/myparcelnl/woocommerce/issues/275)
But great to have this fixed!  Don't want that on Black Friday to happen.

In our case we offer:  ship to home address and pick up location.

The 'ship to address' doesn't depend on API.  Pick up yes. I suggest to check for availability API before calling the function in checkout. 

![image](https://user-images.githubusercontent.com/19552989/68669514-030b9c00-054b-11ea-9a78-f44bcbd5422f.png)

**Comment by RichardPerdaan** [comment]
Unfortunately, the 'ship to address' also uses the API. The times shown in your screenshot are from PostNL. This means that different times may be visible for each location / street in the Netherlands.

And the options morning and evening delivery will also only be possible through the API. 
This data will also be possible per location / street.

So for 'ship to address' there is a API call needed.

I do agree that a solution must be found for this. However, we are already working on this, based on a completely new version of the WooCommerce MyParcel plugin. Unfortunately, this version is not coming live this year.

For a quick solution I add a check in version 3.1.8 of the WooCommerce MyParcel plugin. This problem is therefore no longer occur.
