### ISSUE TITLE
WooCommerce PDF Invoices & Packing Slips placeholders compatibility (#441) Fixe becomes Error :(

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#484]
WooCommerce PDF Invoices & Packing Slips Premium Templates compatibility
The {{myparcel_delivery_date}} placeholder got left out in the 4.0 upgrade (while it was present in 3.x). I wasn't sure whether to place it in includes/compatibility/class-wcpdf-compatibility.php or includes/frontend/class-wcmp-frontend.php but since the former appears to be used specifically for the track & trace placeholders I opted for the latter. Might be good to bundle them all together in the compatibility class after all?

Several bugs in the other placeholder methods are also addressed.

Was adressed as FIXED, but now get this error when make a Pakbon:

![image](https://user-images.githubusercontent.com/29940263/100519349-9d12a680-3197-11eb-8366-214fc3e11ed0.png)

**Comment by Spreeuw** [comment]
This error arose due to the typehinting of `string` in the hooked function ([source](https://github.com/myparcelnl/woocommerce/blob/v4.1.4/includes/frontend/class-wcmp-frontend.php#L93)), which was introduced in #474 but not present in the original PR (#411). The `wpo_wcpdf_templates_replace_{$placeholder}` hooks first argument could be either `null` (default) or a string (if already filtered by another plugin).
In version 2.9.13 of WooCommerce PDF Invoices & Packing Slips Premium Templates this is now an empty string instead of null so that this does not require any changes in the MyParcel plugin.
