### ISSUE TITLE
MyParcel delivery options stay persistent after deselecting.

### ISSUE THREAD

**Issue by onlinemusketeers** [myparcelnl/woocommerce#552]
After selecting different shipping option. MyParcel delivery options stay persistent.  

They need to disappear after deselecting MyParcel. 

![image](https://user-images.githubusercontent.com/19552989/106311481-83f4a780-6265-11eb-8e37-11fd59f9040b.png)

**Comment by RichardPerdaan** [comment]
Hi @onlinemusketeers ,
thank you for posting your message.
We have fixed this in a new version of the MyParcel WooCommerce plugin. You can download this version via the following link: https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0

You could use the following link to download the plugin right away: https://github.com/myparcelnl/woocommerce/releases/download/v4.2.0/woocommerce-myparcel.zip

The reason it isn't available through the regular update yet, is because this is a large release. We are currently testing this version with a number of customers. If you want to use this version, I would advise you to test it first via a staging environment.

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin
