### ISSUE TITLE
As a client I would like to be able to edit Evening & Morning delivery options in my open orders

### ISSUE THREAD

**Issue by bbrassem** [myparcelnl/woocommerce#839]
### What problem does this feature solve?

This feature would let WooCommerce Myparcel users select and deselect morning and evening delivery options in the order. 

That way if the customer asks the webshop owner for an evening delivery after the order was already placed, the webshop owner can choose to still add it before creating a shipping label without having to create a new order.

Bug:
On top of that, it is currently possible to enable morning/evening delivery without showing a delivery date in the checkout. This results in an error when trying to create the shipping label, saying that a delivery date needs to be set for morning/evening delivery. Being able to add a delivery date afterwards or changing it to a standard delivery afterwards would be great, as you currently have no other option but to create the order again manually.

Additionally in the previously described scenario it might be a good idea to just select the nearest possible date (taking into account the selected cutoff time) when there is no delivery date set for the morning/evening delivery.

<img width="1909" alt="Schermafbeelding 2022-06-16 om 11 00 44" src="https://user-images.githubusercontent.com/100422476/174034330-0a45609d-93f5-4f35-b097-0ff4e7f855d5.png">

### What should the solution look like?

In the dropdown menu for editing the shipment details of the order you should be able to change a 'Standard delivery' to a morning/evening delivery and vice versa.

<img width="1920" alt="Schermafbeelding 2022-06-16 om 10 45 31" src="https://user-images.githubusercontent.com/100422476/174033606-189ae0b6-244d-4771-a98e-e2ee59163600.png">

**Comment by wthijmen** [comment]
Hi @bbrassem,

We could not implement this feature because the end customer probably already paid for morning/evening delivery at the checkout.

If you want to get this working in your own environment you can go to **includes/admin/OrderSettingsRows.php** and then **getOptionRows** function. In here you can see the second row with the `'name' => self::OPTION_DELIVERY_TYPE`. Inside this part of the array you can remove the:
`'custom_attributes' => ['disabled' => 'disabled']`

Now it is possible to change the type of delivery at the form.
